<a href="https://colab.research.google.com/github/kishore779/Pytorch_Programming/blob/main/Pytorch_00_excersises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Create a random tensor with shape (7, 7).

In [2]:
import torch

tensor = torch.rand(7,7)
tensor

tensor([[0.8650, 0.0438, 0.6831, 0.6451, 0.1212, 0.9463, 0.3405],
        [0.5833, 0.9519, 0.9122, 0.4772, 0.2751, 0.1962, 0.5735],
        [0.1823, 0.2267, 0.1582, 0.3352, 0.3590, 0.4233, 0.2639],
        [0.9274, 0.2658, 0.5413, 0.1516, 0.5651, 0.3628, 0.0149],
        [0.2578, 0.8781, 0.1481, 0.4594, 0.6535, 0.2072, 0.2987],
        [0.3318, 0.9566, 0.8139, 0.7744, 0.9288, 0.3574, 0.1004],
        [0.3770, 0.2801, 0.9533, 0.8606, 0.1900, 0.8707, 0.3022]])

##Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [5]:
tensor_B = torch.rand(1,7)
tensor_B

torch.matmul(tensor, tensor_B.T)

tensor([[2.0716],
        [2.2324],
        [1.3876],
        [1.4148],
        [2.0075],
        [2.7913],
        [2.4204]])

##Set the random seed to 0 and do 2 & 3 over again

In [12]:
import torch

seed_value = 0
torch.manual_seed(seed_value)

tensor_A = torch.rand(7, 7)

torch.manual_seed(seed_value)
tensor_B = torch.rand(1, 7)

result = torch.matmul(tensor_A, tensor_B.T)
print(result)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


##Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [13]:
import numpy as np
import random

seed = 1234

random.seed(seed)

np.random.seed(seed)



##Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
torch.manual_seed(1234)

x = torch.rand(2,3)
y = torch.rand(2,3)

device = "cuda" if torch.cuda.is_available() else "cpu"

x = x.to(device)
y = y.to(device)

print("Device: ",device)
print(x ,"\n" ,y)


Device:  cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') 
 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


## Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [4]:
multi = torch.matmul(x, y.T)
print(multi,multi.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


## Find the maximum and minimum values of the output of 7.

In [6]:
mini = torch.min(multi)
maxi = torch.max(multi)

print(mini,maxi)

tensor(0.3647, device='cuda:0') tensor(0.5617, device='cuda:0')


##Find the maximum and minimum index values of the output of 7.

In [11]:
minInd = torch.argmin(multi)
maxInd = torch.argmax(multi)
print(minInd.item(), maxInd.item())

0 3


In [17]:
import torch

random_seed = 7

torch.manual_seed(random_seed)
x = torch.rand(1,1,1,10)
x,x.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [18]:
squeed_x = torch.squeeze(x)
squeed_x,squeed_x.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))