<a href="https://colab.research.google.com/github/kishore779/Pytorch_Programming/blob/main/Pytorch_00_programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch Learning in Deep Learning----



In [ ]:
!pip install torch torchvision torchaudio



In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Introduction to Pytorch

## Creating Tensors

In [ ]:
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim


0

In [ ]:
scalar.item()



7

In [ ]:
vector = torch.tensor([7,9])
vector

tensor([7, 9])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8]
                       ,[8,9]])
MATRIX

tensor([[7, 8],
        [8, 9]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSORS = torch.tensor([[[2,3,4],
                        [3,4,5],
                        [6,7,8]]])
TENSORS

tensor([[[2, 3, 4],
         [3, 4, 5],
         [6, 7, 8]]])

In [ ]:
TENSORS.ndim

3

In [ ]:
TENSORS.shape

torch.Size([1, 3, 3])

In [ ]:
TENSORS1 = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
TENSORS1


tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
TENSORS1.shape

torch.Size([3, 2])

In [ ]:
TENSORS1[0]

tensor([1, 2])

`Radomized Tensor Creating`

In [ ]:
random_tensor = torch.rand(1,5,5)
random_tensor

tensor([[[0.9090, 0.0636, 0.9962, 0.0333, 0.5842],
         [0.0355, 0.6874, 0.1126, 0.7479, 0.2415],
         [0.1115, 0.6788, 0.9833, 0.0143, 0.2252],
         [0.4470, 0.4183, 0.7919, 0.4846, 0.4946],
         [0.1940, 0.8109, 0.5809, 0.9092, 0.1973]]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a tensor with similar shape of the image

random_image_sizetensor = torch.rand(size=(224,224,3))
random_image_sizetensor.shape,random_image_sizetensor.ndim

(torch.Size([224, 224, 3]), 3)