<a href="https://colab.research.google.com/github/kishore779/Pytorch_Programming/blob/main/Pytorch_00_programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch Learning in Deep Learning----



In [ ]:
!pip install torch torchvision torchaudio



In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Introduction to Pytorch

## Creating Tensors

In [ ]:
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim


0

In [ ]:
scalar.item()



7

In [ ]:
vector = torch.tensor([7,9])
vector

tensor([7, 9])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8]
                       ,[8,9]])
MATRIX

tensor([[7, 8],
        [8, 9]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSORS = torch.tensor([[[2,3,4],
                        [3,4,5],
                        [6,7,8]]])
TENSORS

tensor([[[2, 3, 4],
         [3, 4, 5],
         [6, 7, 8]]])

In [ ]:
TENSORS.ndim

3

In [ ]:
TENSORS.shape

torch.Size([1, 3, 3])

In [ ]:
TENSORS1 = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
TENSORS1


tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
TENSORS1.shape

torch.Size([3, 2])

In [ ]:
TENSORS1[0]

tensor([1, 2])

`Radomized Tensor Creating`

In [ ]:
random_tensor = torch.rand(1,5,5)
random_tensor

tensor([[[7.0733e-04, 3.8805e-01, 1.6481e-02, 1.2238e-01, 9.5564e-01],
         [8.5510e-01, 6.1864e-01, 1.5006e-01, 7.2737e-01, 5.0048e-01],
         [7.2006e-02, 4.1108e-02, 3.9083e-01, 5.5386e-02, 5.4488e-01],
         [3.4813e-01, 4.2676e-01, 9.5633e-01, 9.0608e-01, 9.6102e-01],
         [4.7610e-01, 1.9906e-01, 1.6402e-02, 5.6947e-01, 8.3442e-01]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
#create a tensor with similar shape of the image

random_image_sizetensor = torch.rand(size=(224,224,3))
random_image_sizetensor.shape,random_image_sizetensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
##crating a range of tensors ans tensors-like
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensors datatypes

``tensor datatypes is one of the 3 big errors you'll run into with pytorch and DL

1.not right datatype
2.not right shape
3.not on the right device


In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

##Getting Info from tensors..


In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0275, 0.1375, 0.5032, 0.4135],
        [0.5137, 0.7177, 0.2646, 0.7077],
        [0.9273, 0.1329, 0.3555, 0.9067]])

In [ ]:
##find details about tensors..

print(some_tensor)
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of tensors: {some_tensor.shape}")
print(f"Device of tensors: {some_tensor.device}")

tensor([[0.0275, 0.1375, 0.5032, 0.4135],
        [0.5137, 0.7177, 0.2646, 0.7077],
        [0.9273, 0.1329, 0.3555, 0.9067]])
DataType of tensor: torch.float32
Shape of tensors: torch.Size([3, 4])
Device of tensors: cpu


### Manipulating tensors

Operations
1.Addition
2.Subtraction
3.Multiplication
4.division
5.matrix multiplication


In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
# matrix mul

torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
# scalar multiplication
tensor @ tensor

tensor(14)

In [ ]:
torch.matmul(torch.rand(3,10) , torch.rand(10,3))

tensor([[2.4959, 3.8446, 3.7952],
        [2.7497, 4.1879, 4.5123],
        [2.0423, 3.2878, 3.9055]])

In [ ]:
torch_A = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
torch_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
# transverse
torch_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

##To find min,max,sum,count etc


In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

##positional values to find in x


In [ ]:
torch.argmin(x)

tensor(0)

In [ ]:
torch.argmax(x)


tensor(9)

## Reshaping, shaping, sqeezing and unsqueezing

In [ ]:
y = torch.arange(1.,10.)
y,y.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
y_reshaped = y.reshape(9,1)
y_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
z = y.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([y,y,y,y], dim =1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_squeezed = y.squeeze()
x_squeezed,x_squeezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_unsqeezed = x_squeezed.unsqueeze(dim=0)
x_unsqeezed,x_unsqeezed.shape
#

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_original = torch.rand(size=(224,224,3))

x_permuted = x_original.permute(2,0,1)
print(f"previous shape = {x_original.shape}")
print(f"permuted shape = {x_permuted.shape}")

previous shape = torch.Size([224, 224, 3])
permuted shape = torch.Size([3, 224, 224])


In [ ]:
x_original

tensor([[[0.0163, 0.4622, 0.3353],
         [0.9018, 0.6829, 0.1207],
         [0.3087, 0.2758, 0.8682],
         ...,
         [0.4077, 0.0201, 0.5579],
         [0.8747, 0.5311, 0.1605],
         [0.5656, 0.0466, 0.5637]],

        [[0.9511, 0.9246, 0.8776],
         [0.6037, 0.7306, 0.1490],
         [0.6391, 0.2972, 0.5124],
         ...,
         [0.3963, 0.9387, 0.1470],
         [0.7794, 0.3964, 0.4331],
         [0.7709, 0.4750, 0.0169]],

        [[0.8907, 0.0133, 0.0111],
         [0.0205, 0.5588, 0.0808],
         [0.4035, 0.2294, 0.8153],
         ...,
         [0.9461, 0.1002, 0.5116],
         [0.9401, 0.9191, 0.5589],
         [0.7679, 0.7900, 0.3224]],

        ...,

        [[0.0765, 0.6250, 0.2177],
         [0.4571, 0.4701, 0.0777],
         [0.0728, 0.2814, 0.6457],
         ...,
         [0.7231, 0.0085, 0.8875],
         [0.5223, 0.9599, 0.8170],
         [0.5010, 0.3010, 0.7555]],

        [[0.9076, 0.2796, 0.0872],
         [0.6775, 0.6079, 0.9424],
         [0.

In [ ]:
x_original[0,0,0]

tensor(0.0163)

##Indexing in pytorch

In [ ]:
import torch
tensor = torch.arange(1,10).reshape(1,3,3)
tensor,tensor.size()

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
tensor[0][0]

tensor([1, 2, 3])

In [ ]:
tensor[0][0][0]

tensor(1)

In [ ]:
tensor[0][2][2]

tensor(9)

In [ ]:
tensor[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors and Numpy

In [ ]:
## numpy to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array + 1,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
## tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor + 1,tensor

(array([2., 2., 2., 2., 2., 2., 2.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

## Reproducability (trying to take random out of random)

In [ ]:
import torch

random_tensorA = torch.rand(3,4)
random_tensorB = torch.rand(3,4)

print(random_tensorA)
print(random_tensorB)
print(random_tensorA == random_tensorB)

tensor([[0.3874, 0.3374, 0.0744, 0.2596],
        [0.5465, 0.1894, 0.4352, 0.5588],
        [0.5844, 0.6114, 0.6256, 0.2947]])
tensor([[0.2197, 0.7653, 0.4342, 0.1539],
        [0.1057, 0.9473, 0.2386, 0.4300],
        [0.3769, 0.5712, 0.5763, 0.1267]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
## make some reproducible tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensorC = torch.rand(3,4)
random_tensorD = torch.rand(3,4)

print(random_tensorC)
print(random_tensorD)
print(random_tensorC == random_tensorD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Using gpu for faster Accesss

In [2]:
!nvidia-smi

Fri Jan  2 02:34:03 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

##1.Check for GPU acces

In [4]:
import torch
torch.cuda.is_available()

True

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [11]:
torch.cuda.device_count()

1

##2.Putting sensors on the gpu

In [14]:
tensor = torch.tensor([1,2,4])

print(tensor, tensor.device)

tensor([1, 2, 4]) cpu


In [15]:
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 4], device='cuda:0')

##3. Moving tensor to cpu

In [16]:
## numpy doesn't work on numpy

tensor_backon_cpu = tensor_gpu.cpu().numpy()
tensor_backon_cpu

array([1, 2, 4])