<a href="https://colab.research.google.com/github/kishore779/Pytorch_Programming/blob/main/Pytorch_00_programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch Learning in Deep Learning----



In [ ]:
!pip install torch torchvision torchaudio



In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Introduction to Pytorch

## Creating Tensors

In [ ]:
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim


0

In [ ]:
scalar.item()



7

In [ ]:
vector = torch.tensor([7,9])
vector

tensor([7, 9])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8]
                       ,[8,9]])
MATRIX

tensor([[7, 8],
        [8, 9]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSORS = torch.tensor([[[2,3,4],
                        [3,4,5],
                        [6,7,8]]])
TENSORS

tensor([[[2, 3, 4],
         [3, 4, 5],
         [6, 7, 8]]])

In [ ]:
TENSORS.ndim

3

In [ ]:
TENSORS.shape

torch.Size([1, 3, 3])

In [ ]:
TENSORS1 = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
TENSORS1


tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
TENSORS1.shape

torch.Size([3, 2])

In [ ]:
TENSORS1[0]

tensor([1, 2])

`Radomized Tensor Creating`

In [ ]:
random_tensor = torch.rand(1,5,5)
random_tensor

tensor([[[0.5154, 0.1216, 0.7734, 0.5563, 0.1727],
         [0.3345, 0.9858, 0.2812, 0.4390, 0.7763],
         [0.8804, 0.3576, 0.5728, 0.2219, 0.8584],
         [0.5550, 0.1637, 0.4071, 0.8925, 0.1703],
         [0.7663, 0.4979, 0.4387, 0.8817, 0.7220]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
#create a tensor with similar shape of the image

random_image_sizetensor = torch.rand(size=(224,224,3))
random_image_sizetensor.shape,random_image_sizetensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
##crating a range of tensors ans tensors-like
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensors datatypes

``tensor datatypes is one of the 3 big errors you'll run into with pytorch and DL

1.not right datatype
2.not right shape
3.not on the right device


In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

##Getting Info from tensors..


In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6036, 0.3193, 0.7940, 0.6517],
        [0.2407, 0.9597, 0.8367, 0.4230],
        [0.9981, 0.3438, 0.6198, 0.3130]])

In [ ]:
##find details about tensors..

print(some_tensor)
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of tensors: {some_tensor.shape}")
print(f"Device of tensors: {some_tensor.device}")

tensor([[0.6036, 0.3193, 0.7940, 0.6517],
        [0.2407, 0.9597, 0.8367, 0.4230],
        [0.9981, 0.3438, 0.6198, 0.3130]])
DataType of tensor: torch.float32
Shape of tensors: torch.Size([3, 4])
Device of tensors: cpu


### Manipulating tensors

Operations
1.Addition
2.Subtraction
3.Multiplication
4.division
5.matrix multiplication


In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
# matrix mul

torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
# scalar multiplication
tensor @ tensor

tensor(14)

In [ ]:
torch.matmul(torch.rand(3,10) , torch.rand(10,3))

tensor([[3.3690, 2.4156, 3.2037],
        [2.6328, 2.2496, 3.1447],
        [3.5234, 2.5922, 2.9195]])

In [ ]:
torch_A = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
torch_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
# transverse
torch_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

##To find min,max,sum,count etc


In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

##positional values to find in x


In [ ]:
torch.argmin(x)

tensor(0)

In [ ]:
torch.argmax(x)


tensor(9)

## Reshaping, shaping, sqeezing and unsqueezing

In [ ]:
y = torch.arange(1.,10.)
y,y.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
y_reshaped = y.reshape(9,1)
y_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
z = y.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [68]:
x_stacked = torch.stack([y,y,y,y], dim =1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [71]:
x_squeezed = y.squeeze()
x_squeezed,x_squeezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [74]:
x_unsqeezed = x_squeezed.unsqueeze(dim=0)
x_unsqeezed,x_unsqeezed.shape
#

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
x_original = torch.rand(size=(224,224,3))

x_permuted = x_original.permute(2,0,1)
print(f"previous shape = {x_original.shape}")
print(f"permuted shape = {x_permuted.shape}")

previous shape = torch.Size([224, 224, 3])
permuted shape = torch.Size([3, 224, 224])


In [76]:
x_original

tensor([[[0.9425, 0.6111, 0.4093],
         [0.3704, 0.3987, 0.2206],
         [0.0679, 0.0539, 0.6401],
         ...,
         [0.8223, 0.2358, 0.1361],
         [0.2962, 0.9557, 0.9474],
         [0.7093, 0.4018, 0.3993]],

        [[0.6085, 0.2375, 0.0424],
         [0.3849, 0.4794, 0.7531],
         [0.5873, 0.4047, 0.2262],
         ...,
         [0.9711, 0.8961, 0.4485],
         [0.2779, 0.3160, 0.8256],
         [0.4884, 0.1740, 0.6415]],

        [[0.3655, 0.5489, 0.3798],
         [0.9236, 0.2832, 0.1567],
         [0.5373, 0.7694, 0.2956],
         ...,
         [0.9413, 0.6107, 0.4816],
         [0.9994, 0.9866, 0.4624],
         [0.8504, 0.4242, 0.6442]],

        ...,

        [[0.6532, 0.3455, 0.7464],
         [0.0825, 0.3295, 0.7152],
         [0.9762, 0.0962, 0.4262],
         ...,
         [0.2187, 0.4385, 0.0540],
         [0.9763, 0.9133, 0.7591],
         [0.7461, 0.3403, 0.2822]],

        [[0.7074, 0.9283, 0.5225],
         [0.4324, 0.7271, 0.7617],
         [0.